name: Release new version

on: 
  workflow_dispatch:
    inputs:
      type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
        - major
        - minor
        - fix
        - preview
        - release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install hatch

      - name: setup git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Bump Version
        run: |
          hatch version $TYPE
          git commit -am "Release v$(hatch version)"
        env:
          TYPE: ${{ inputs.type }}

      - name: Create Git Tag
        run: git tag v$(hatch version)

      - name: Print version
        run: hatch version

      - name: Print log
        run: git log --oneline -n10

      - name: Push Changes
        run: |
          git push origin --all
          git push origin --tags

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          # tag_name: v$(hatch version)
          generate_release_notes: true

      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
