name: Run Pytest

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install hatchling
        run: |
          python -m pip install --upgrade hatchling
      - name: Install dependencies
        run: |
          hatchling install
      - name: Set environment variable using secret
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
      - name: Run test suite
        run: |
          pytest -v
