name: tests

on:
  push:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install -e .[dev]
      - name: Check style
        run: black --check --diff .
      - name: chek types
        run: mypy .
      - name: Run test suite
        run: pytest -v
